# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOMUCHSPACE/Works/CW/CW.srcs/sources_1/ip/Head_Bullet5/Head_Bullet5.xci
# IP: The module: 'Head_Bullet5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOMUCHSPACE/Works/CW/CW.gen/sources_1/ip/Head_Bullet5/Head_Bullet5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Head_Bullet5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/SOMUCHSPACE/Works/CW/CW.srcs/sources_1/ip/Head_Bullet5/Head_Bullet5.xci
# IP: The module: 'Head_Bullet5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOMUCHSPACE/Works/CW/CW.gen/sources_1/ip/Head_Bullet5/Head_Bullet5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Head_Bullet5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
