# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOMUCHSPACE/Works/CW/CW.srcs/sources_1/ip/Bar1/Bar1.xci
# IP: The module: 'Bar1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOMUCHSPACE/Works/CW/CW.gen/sources_1/ip/Bar1/Bar1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bar1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/SOMUCHSPACE/Works/CW/CW.srcs/sources_1/ip/Bar1/Bar1.xci
# IP: The module: 'Bar1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SOMUCHSPACE/Works/CW/CW.gen/sources_1/ip/Bar1/Bar1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bar1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
