# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/SOMUCHSPACE/Works/Lab 3/Lab 3.srcs/constrs_1/imports/Vivado/Nexys-4-DDR-Master.xdc

# IP: ip/Top_Bullet4/Top_Bullet4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Bullet4 || ORIG_REF_NAME==Top_Bullet4} -quiet] -quiet

# IP: ip/Top_Bullet3/Top_Bullet3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Bullet3 || ORIG_REF_NAME==Top_Bullet3} -quiet] -quiet

# IP: ip/Top_Bullet2/Top_Bullet2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Bullet2 || ORIG_REF_NAME==Top_Bullet2} -quiet] -quiet

# IP: ip/Head_Bullet3/Head_Bullet3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Head_Bullet3 || ORIG_REF_NAME==Head_Bullet3} -quiet] -quiet

# IP: ip/hBulletTwo/hBulletTwo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hBulletTwo || ORIG_REF_NAME==hBulletTwo} -quiet] -quiet

# IP: ip/Head_Bullet/Head_Bullet.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Head_Bullet || ORIG_REF_NAME==Head_Bullet} -quiet] -quiet
